### PR TITLE
Removed extra blank space on footer and updated style.css

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by mrmattmueller** [comment]
The spaces are on purpose and have been selected by intend, thus they're wanted by the Org.

**Comment by ghost** [comment]
Okay I will update it.

**Comment by mrmattmueller** [comment]
Hi,
Thank you for your support! :)
However, we're currently working on introducing a new website with CMS and based on other open source frameworks. Thus, please don't but too much effort into it since chances are high that these pages will be replaced very soon ;)

**Comment by ghost** [comment]
Please can I work on the new site user-interface (UI) and user-experience (UX) design?

**Pull request closed without merging**
